FROM python:3.12-slim

WORKDIR /app

COPY pyproject.toml .

RUN pip install --no-cache-dir -e "."

COPY app/ app/

EXPOSE 8501

ENV BASE_URL=http://backend:8000/

CMD ["streamlit", "run", "app/frontend/main.py", "--server.address=0.0.0.0", "--server.port=8501"]
